"""add payments and payment_items tables

Revision ID: 1285a8d1c787
Revises: 309386534115
Create Date: 2025-08-22 22:28:28.618317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1285a8d1c787"
down_revision: Union[str, Sequence[str], None] = "309386534115"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies_directors")
    op.drop_table("certifications")
    op.drop_table("movie_likes")
    op.drop_table("orders")
    op.drop_table("movies_stars")
    op.drop_table("user_group")
    op.drop_table("activation_token")
    op.drop_table("movie_comments")
    op.drop_table("password_reset_token")
    op.drop_table("movies_genres")
    op.drop_table("order_items")
    op.drop_table("user")
    op.drop_table("refresh_token")
    op.drop_table("cart_items")
    op.drop_table("carts")
    op.drop_table("user_profile")
    op.drop_table("stars")
    op.drop_table("user_favorites")
    op.drop_table("movie_ratings")
    op.drop_table("directors")
    op.drop_table("movies")
    op.drop_table("genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("uuid", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(length=250), nullable=False),
        sa.Column("year", sa.INTEGER(), nullable=False),
        sa.Column("time", sa.INTEGER(), nullable=False),
        sa.Column("imdb", sa.FLOAT(), nullable=False),
        sa.Column("votes", sa.INTEGER(), nullable=False),
        sa.Column("meta_score", sa.FLOAT(), nullable=True),
        sa.Column("gross", sa.FLOAT(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("certification_id", sa.INTEGER(), nullable=False),
        sa.Column("is_available", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "directors",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movie_ratings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("rating", sa.INTEGER(), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 10", name=op.f("rating_range")),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_favorites",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "movie_id"),
    )
    op.create_table(
        "stars",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("avatar", sa.VARCHAR(length=255), nullable=True),
        sa.Column("gender", sa.VARCHAR(length=5), nullable=True),
        sa.Column("date_of_birth", sa.DATETIME(), nullable=True),
        sa.Column("info", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "carts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("cart_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("added_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=255), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("group_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("price_at_order", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movies_genres",
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("genre_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "genre_id"),
    )
    op.create_table(
        "password_reset_token",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "movie_comments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activation_token",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_group",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=9), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "movies_stars",
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("star_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["star_id"],
            ["stars.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "star_id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=8), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movie_likes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certifications",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movies_directors",
        sa.Column("movie_id", sa.INTEGER(), nullable=False),
        sa.Column("director_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["directors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "director_id"),
    )
    # ### end Alembic commands ###
